apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
  namespace: "{{ meta.namespace }}"
spec:
  replicas: {{ replicas | int }}
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: "busybox:{{ image_tag }}"
        command:
        - sh
        - "-c"
        -  "sleep 4800"
        name: nginx
        resources: {}
status: {}
